### ISSUE TITLE
Telegram Bot for Sport

### ISSUE THREAD

**Issue by evermake** [one-zero-eight/roadmap#3]
### Summary

It would be great to have a Telegram Bot as an alternative to [website](https://sport.innopolis.university/profile/). Advantages over the website:

- Instant authentication w/o login process.
- Notifications as Telegram messages about upcoming sport sessions.
- More user-friendly interface with Telegram messages or Mini App.

**Comment by ArtemSBulgakov** [comment]
This is work in progress in [sport-bot](https://github.com/one-zero-eight/sport-bot) repository.

This issue will be marked as closed after the public release of the bot.

**Comment by evermake** [comment]
https://t.me/one_zero_eight/60
