### ISSUE TITLE
Room booking: New service for students

### ISSUE THREAD

**Issue by ArtemSBulgakov** [one-zero-eight/roadmap#9]
### Summary

Current room booking service on My University requires a lot of time to find a suitable room and book that room.

We should create a convenient interface for viewing the list of bookings of each room and for booking that room. It should be easy for users to quickly find the free room and book it.

**Comment by ArtemSBulgakov** [comment]
Some effort is done in https://github.com/one-zero-eight/room-booking and https://github.com/one-zero-eight/website/tree/main/src/components/room-booking.

**Comment by evermake** [comment]
@ArtemSBulgakov, done?

**Comment by ArtemSBulgakov** [comment]
The service is published for students: https://t.me/one_zero_eight/95
